name: pytest for irspack
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Build irspack (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install lcov
          IRSPACK_TESTING="true" python setup.py develop
      - name: Build irspack (other)
        if: matrix.os != 'ubuntu-latest'
        run: |
          python setup.py develop
      - name: Run pytest
        run: |
          pip install pytest pytest-cov
          pip install lightfm jaxlib jax dm-haiku optax
          curl http://files.grouplens.org/datasets/movielens/ml-100k.zip -o $HOME/.ml-100k.zip
          pytest --cov=./irspack tests/
      - name: Generate coverage (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          coverage xml
          lcov -d `pwd` -c -o coverage.info
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7'
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml,./coverage.info
          verbose: false
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
