name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Generate coverage report
        run: |
          sudo apt-get install wget lcov
          pip install pytest pytest-cov
          pip install lightfm jaxlib jax dm-haiku optax
          wget http://files.grouplens.org/datasets/movielens/ml-100k.zip -O $HOME/.ml-100k.zip
          IRSPACK_TESTING="true" python setup.py develop
          rm -rf eigen-3.3.7
          pytest --cov=./irspack --cov-report=xml
          lcov -d `pwd` -c -o coverage.info
          lcov -e coverage.info */cpp_source/* -o coverageFiltered.info
          echo `ls -ltr`
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml, ./coverage.info
          verbose: false
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
