name: Test tutorial example
on: [push, pull_request]
jobs:
  run_tutorials:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Build irspack (ubuntu)
        run: |
          pip install --upgrade pip
          sudo apt-get install lcov
          python setup.py install
      - name: Run pytest
        run: |
          pip install jupyter
          cd examples
          for file in \
            train-first-recommender \
            evaluate-recommender \
            hyperparameter-optimization \
          ; do
            jupyter nbconvert --to script "${file}.ipynb"
            echo "Start running ${file}.py"
            if ! python "${file}.py" ; then
              echo "executiion of \"${file}.ipynb\" failed."
              exit 1;
            fi
          done
